### ISSUE TITLE
(Vita) Wario Ware Twisted (U) - Crash during Dribble & Spitz end cutscene

### ISSUE THREAD

**Issue by lKomus** [libretro/vba-next#76] opened 2016-11-19 20:15 UTC
This crash occurs with the latest nightly, it happens when the space taxi cab go offscreen. Since the cutscene is unskippable, I can't progress in the game anymore.
There's another crash in this game with a Mona mini-game but I'm unable to tell which one because it crashes before it appears.

This contains the crash dump generated by the Vita and the savestate before the crash: 
[vita_wwt_crash.zip](https://github.com/libretro/vba-next/files/601705/vita_wwt_crash.zip)

**Comment by SHIuSH** [comment] 2017-09-03 06:45
same happens to me. tried different roms from different sources. still crashes

**Comment by retro-wertz** [comment] 2018-05-30 09:04
took a long time, but this issue should already be fixed in latest commit.

the problem is related to this https://github.com/libretro/vba-next/issues/93, which already has been fixed a few commits ago.

![2](https://user-images.githubusercontent.com/23315382/40710525-76d73e9a-642b-11e8-98c5-8f0629ed7ad4.png)

**Comment by hizzlekizzle** [comment] 2018-05-30 16:19
ok, gonna close this, then. Feel free to reopen if something changes.

**Closed by hizzlekizzle** 2018-05-30 16:19 UTC
